export const numbers = [   
    {   id: 1,
        content: '7',
    },
    {   id: 2,
        content: '8',
    }, 
    {   id: 3,
        content: '9',
    }, 
    {   id: 4,
        content: '4',
    }, 
    {   id: 5,
        content: '5',
    },
    {   id: 6,
        content: '6',
    }, 
    {   id: 7,
        content: '1',
    }, 
    {   id: 8,
        content: '2',
    }, 
    {   id: 9,
        content: '3',
    }, 
    {   id: 10,
        content: '.',
    }, 
    {   id: 11,
        content: '0',
    }, 
]
export const operand = [
    {   id: 1,
        content: '/',
    },
    {   id: 2,
        content: '*',
    }, 
    {   id: 3,
        content: '-',
    }, 
    {   id: 4,
        content: '+',
    }, 
]

export const original = ['.', '/', '+', '-', '+/-', '*']